jango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
]

music/urls.py
from django.urls import path
from . import views
app_name ="music"

urlpatterns = [
    path('', views.index, name = "index"),       #blank url    http://127.0.0.1
    path('music/', views.index, name="index"),  # http://127.0.0.1/music
    path('<int:id>/', views.detail, name ="detail"),
    path('<int:id>/favorite', views.favorite, name ="favorite"),
    path('email/', views.emailer, name ="emailer"),
    path('result/',views.result,name ="result"),
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length = 100)
    album_logo = models.CharField(max_length =1000)
    def __str__(self):
        return self.album_title+"-"+self.artist
        
class song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length =10)
    song_title = models.CharField(max_length = 250)
    is_favorite  = models.BooleanField(default = False)

    def __str__(self):
        return self.song_title

music/views.py
# from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album,song

def index(request):
    all_album = Album.objects.all()
    # html ='<ul>'
    # for album in all_album:
    #     html = html+"<li><a href='/"+str(album.id)+ "'>"+ album.artist +" </a></li>"
    # html +='</ul>'
    # template = loader.get_template('music/index.html')
    # context = {'all_album':all_album}
    return render(request,'music/index.html',{'all_album':all_album})

def detail(request,id):
    # try:
    #     album = Album.objects.get(pk=id)
    # except Album.DoesNotExist:
    #     raise Http404("Album does not exist...Try again")
    album = get_object_or_404(Album,pk=id)
    return render(request,'music/detail.html',{'album':album})

def favorite(request,id):
    album = get_object_or_404(Album,pk=id)
    try:
        selected_song = album.song_set.get(pk = request.POST['song'])
    except (KeyError,song.DoesNotExist):
        return(request,'music/detail.html',{'album':album,'error_message':"You did not selected a valid song"})
    else:
        if selected_song.is_favorite:
            selected_song.is_favorite = False
        else:
            selected_song.is_favorite = True
        selected_song.save()
        return render(request,'music/detail.html',{'album':album})

def emailer(request):
    return render(request,'music/email.html',{})

def result(request):
    name = request.POST['name']
    email = request.POST['email']
    msg  = request.POST['msg']
    context = {'name':name,'email':email,'msg':msg}
    return render(request,'music/result.html',context)

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %} Cloud Music Player _ Devloped using Django{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-reboot.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-grid.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="{% url 'music:emailer' %}" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container-fluid d-flex justify-content-between">
          <a href="{% url 'music:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

	<div class="container-fluid">
		{% block body %}
		{% endblock %}
	</div>
<section id="footer">
    <div class="container-fluid">
        <p><span class="float-left"> Django Music</span> <span class="float-right"> <a href="http://www.cbsetoday.com" target="_blank"> Rakesh Kumar </a></span> </p>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src ="{% static 'js/bootstrap.bundle.js'%}"></script>
    </body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %} 
{% block title %} World Music Player {% endblock %}
{% block body %}

  <img class="img-responsive" src ="{{album.album_logo}}" alt="album Logo" />
  <h1> {{album.album_title}} </h1>
  <h2> {{album.artist}} - {{album.genre}}</h2>
  {% comment %} <ul>
  {% for song in album.song_set.all %}
    <li>{{song.song_title}} - {{song.file_type}}
  {% endfor %}
  </ul> {% endcomment %}
  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <form action ="{% url 'music:favorite' album.id %}" method ="post">
     {% csrf_token %}
     {% for song in album.song_set.all %}
      <input type="radio" id="song-{{ forloop.counter }}" name ="song" value ="{{song.id}}">
      <label for ="song-{{ forloop.counter }}"> {{song.song_title}}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
      </label><br/>
      {% endfor %}
     <input class="btn btn-success" type="submit"  value ="Make This song Favorite">
  </form>
{% endblock %}

music/templates/music/email.html
{% extends 'music/base.html' %} 
{% block title %} Contact us {% endblock %}
{% block body %}
	<div class="container-fluid">
	<h1>Contact us </h1>
	<form action="{% url 'music:result' %}" method ="POST">
	    {% csrf_token %}
		<div class="form-group">
			<label for="exampleInputEmail1">Email address</label>
			<input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
			<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Your Name</label>
			<input type="text" name="name" class="form-control" id="name" placeholder="Enter your Name here">
		</div>
		<div class="form-group">
			<label for="msgbox">Enter Your Message here </label>
			<TextArea class="form-control" name="msg" id="msg" placeholder="Enter your message here" rows="8"></TextArea>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	</div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}	
{% block title %} World Music Player {% endblock %}
{% block body %}
	{% if all_album %}
	    <h2> Here is your all Albums</h2>
	    <div class="container-fluid">
		  <div class="row">
	        {% for album in all_album %}
			    <div class="col-md-4">
				  <div class="card mb-4 box-shadow">
					<img class="card-img-top" src="{{album.album_logo}}" alt ="{{album.album_title}}"/>
					<div class="card-body">
						<a href="{% url 'music:detail' album.id %}"> {{album.album_title}}</a>
					</div>
					</div>
				</div>
	        {% endfor %}
	    </div>
		</div>
	{% else %}
	    <h2> NO Data available to display</h2>
	{% endif %}
{% endblock %}

music/templates/music/result.html
{% extends 'music/base.html' %}
{% block title %} Email Result {% endblock %}

{% block body %}
<H1> Email Result </h1>
<p> Entered Name : {{name}} <br/>
Email  :{{email}} <br/>
message :{{msg}}
{% endblock %}